# SPDX-FileCopyrightText: : 2021
# Prerequisites: Conda-ENV, packages pyyaml / subprocess / sys

# PACKAGE-INSTALLATIONS: False, if conda environment is active and packages are installed, if True: missing packages are installed at the beginning
install_packages: False 

network:
 filename: 'elec_uba17_27.11.nc'
 year: '2050' #reference year
 scenario: "Umweltbundesamt 2050"

evaluation: #evaluation of the residual load in network concentrating on time statistics.
 residual_load_ordered: f
 zero_crossings: f # residual load changing from begative to positive
 duration_line: f # annual duration line
 duration_statistics: f # statistics concerning duration of one phase positive residual load
 load_shifting_simulation: f # easy algorithm simulating load shifting
 signals: true # signals for load-shifting potentials having residual load as basis
 emissions: f #emissions of energy production in AUT in gCO2equ/kWh
